---
title: "Advantages and Drawbacks of using P-values"
---

### Goal of Mini-Project:

Read 'Moving to a world beyond p<0.05' by Wasserstein, Schirm, and Lazar. Answer questions about the reading, dissecting the disadvantages to utilizing p-values and confidence intervals in statistical results. 

## Statement of Integrity 

“All work presented is my own, and I have followed all rules for collaboration. I have not used generative AI on this project.” - Kaitlin Heintzman 

## Towards the end of Section 1, the authors say “As ‘statistical significance’ is used less, statistical thinking will be used more.” Elaborate on what you think the authors mean. Give some examples of what you think embodies “statistical thinking.”

This refers to the idea that statistical significance is reliant upon arbitrarily set values that anybody can deem "important", and this value often decides whether a study is "important" or not. I think the authors really want to critique this approach, and suggest that denoting a study's worth based on this value decreases our true understanding of the science behind it. The authors want to point out that turning away from this method will allow us to focus more on our understanding of the research and results. By distancing ourselves from this method we can think more critically about the theories behind it, the protocol and methods used for analysis, and the results that were found. To me, statistical thinking embodies this approach of critical thinking, and it also refers to understanding the theory behind tests or modeling techniques, knowing your data and how it was collection, and being able to really process what approaches would be beneficial to effectively communicate and analyze your data.  

## Section 2, third paragraph: The authors state “A label of statistical significance adds nothing to what is already conveyed by the value of p ; in fact, this dichotomization of p-values makes matters worse.” Elaborate on what you think the authors means.

I think that this quote is portraying the idea that once you denote whether a p-value is significant or not, you have bestowed the idea that you should find the results important or not important. This quote is pointing out that declaring significance really means nothing, however the way it has been adapted into research has given it so much weight, and the true p-value number stands alone with or without a declaration of "significance". The authors point out in this section that something people do not understand or often forget is the idea that the p-value just relates to the study, it is not a distinction that something is true or false. However that incorrect idea is often assumed due to the way we split p-values into two categories: significant and not significant. This harsh line between the two is harmful because again this value is made up, there is no real reason that 0.04 should be significant, but 0.058 shouldn't be. To discourage this grouping approach, I think the authors want to really convey the idea that even without a label of significance the p-value still can display information to us about a study, and that due to the way we linguistically understand significance, we have transformed this classification (which is unnecessary!) into a very black and white approach to understanding scientific results. 

## Section 2, end of first column: The authors state “For the integrity of scientific publishing and research dissemination, therefore, whether a p-value passes any arbitrary threshold should not be considered at all when deciding which results to present or highlight.” Do you agree or disagree? How should it be decided which results to present/highlight in scientific publishing?

I do agree with this statement, I think that publishing or focusing on only "significant" research would cause people to miss out on other studies which may have interesting conclusions, novel approaches, or new theories. By limiting the presentation of research we also limit the opportunities for studies to be replicated, and we miss out on understanding the full range of scientific possibilities. I will say that I do think that the p-value should be still communicated to your audience when applicable, but it shouldn't be the basis of your results. I think that results should be presented or highlighted if they follow comprehensive protocols and show possible patterns which could be explained scientifically or align with theories/ideas that should be explored more. I think those presenting should be focused less on the threshold the p-value passes, and focus more on understanding the results and how they can affect or change current theories. 

## Section 3, end of page 2: The authors state “The statistical community has not yet converged on a simple paradigm for the use of statistical inference in scientific research – and in fact it may never do so. A one-size-fits-all approach to statistical inference is an inappropriate expectation.” Do you agree or disagree? Explain.

I agree with both of these statements, I think that due to the amount of scientific and humanitarian fields which utilize statistics it is unreasonable to think that there could be just one piece of criteria to judge all of these studies. The differences within fields should prompt us to use more than just one approach because different studies require different skill sets and it would be  beneficial to approach different topics with different ideas in mind. I also think that even within a field there are still so many opinions, and people who may prioritize or argue for different criteria, that it would be unlikely you could agree on just one approach within a community. I also believe this is good, academia and research is a place where I think people should have the freedom to explore theories and to analyze results with different methods, as this will only expand our understanding of these studies. I think generally the norm for analyzing results should be with multiple ideas in mind because this increases not only your understanding, but the types of conclusions you can make. By idolizing one approach we can miss our on things the data may be able to convey to us.

## Section 3.2: The authors note that they are envisioning “a sort of ‘statistical thoughtfulness’.” What do you think “statistical thoughtfulness” means? What are some ways to demonstrate “statistical thoughtfulness” in an analysis?

Statistical thoughtfulness can refer to understanding the study, thinking critically about assumptions, and understanding your models/modeling approaches. This approach enables flexibility in your analysis, which is good as this can help more discoveries arise. Other important aspects to statistical thoughtfulness are asking questions about the study or the protocol to develop a theoretical understanding of your project, and by researching prior beliefs or studies. Lastly an important aspect is making your study reproducible, by doing so you are thinking ahead for those who may want to replicate your study and support/challenge your results. I think being statistically thoughtful includes thinking about the impact of your study, how will it impact what we already know, how will it impact those affected by this study, and how will it impact people who want to continue studying this topic. By including others in our thinking while we preform an analysis I think it increases your range of people you can affect, and it also then contributes more to the scientific field and topic. I think this idea is really important because accessibility and teamwork are really important ideas in the progression of research, and I think that they are things which can often be forgotten.

## Section 3.2.4: A few of the authors of papers in this special issue argue that some of the terminology used in statistics, such as “significance” and “confidence” can be misleading, and they propose the use of “compatibility” instead. What you do you think they believe the problem is? Do you agree or disagree (that there is a problem and that changing the name will help)?

I think that the issue with these specific words is the way that we are known to understand them, and this can cause overconfidence in connection and causation. The words significance and confidence suggest the idea that things are connected, and that we know that connection to be true. This is misleading because in reality p-values or confidence intervals do not tell us any true fact, they are just calculations created from our data. By using the word "compatibility," you suggest the idea that your data aligns with particular idea, but not that it must be true. Honestly, I have a bit of trouble fully agreeing with this argument, I think that there is a problem and that a lot of people probably do take p-values and confidence intervals at face value, believing them to be fact or that they prove something to be true. However, I think that believing that just changing the words to something will likely not solve the problem, and the problem is in the weight and importance we have given to the criteria. I think although it is true these words suggest different things, the main problem lies in the fact that we have limited a lot of research to just the numerical outputs of p-values and confidence intervals. By changing that approach and expanding the amount of criteria we consider and by looking closer at the results themselves, I think we would distribute the weights these values have, and then this issue of terminology may not be so prevalent. 

## Find a quote or point that really strikes you (i.e., made you think). What is the quote (and tell me where to find it), and why does it stand out to you?

The quote that I chose is, "Indeed, there is essentially no aspect of scientific investigation in which judgement is not required," which appears under section 3.3.1 in the second paragraph. I chose this quote because I think it conveys a really important idea about the way that science connects people. I think it can be common that as you research something and dedicate time to it, you don't really want to hear about somebody's judgement or opinion about your choices. However, this quote makes me think about how without that judgement there is no way for you to get better, and the judgement of someone else is what leads to not just the advancement of your ideas, but it keeps the research topic alive. On that topic, this quote also makes me think about the idea that the research everybody carries out is initially due to some type of judgement, whether of another study or a concept. Judgement has likely been a driving force in a majority of our scientific advancements, and this is an idea I really have never thought about. Lastly, I think the word judgement carries a lot of negative connotations, but I like the way that it was used in this quote because it shows how judgement can actually be a really positive and impactful thing. 


