{
  "hash": "edeeee64b658f030e0e0dd2a5129fa05",
  "result": {
    "markdown": "---\ntitle: \"Bayesian Analysis\"\n---\n\n\n### Goal of Mini-Project:\n\nExplore a Bayesian approach to data analysis. Understand how different priors affect posterior distributions. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n\n### Statement of Integrity:\n\n“I have followed all rules for collaboration for this project, and I have not used generative AI on this project.” - Kaitlin Heintzman \n\n## Introduction \n\nThe goal of this project is to try to answer the question \"what is the probability that Rafael Nadal wins a point on his own serve when playing against Novak Djokovic at the French Open?\" by using Bayesian analysis to estimate this unknown parameter and its distribution. In this project, I will use various priors combined with data from the 2020 French Open to construct three posterior distributions, I will analyze the differences that I find along the way and how each distributions predicts the probability of interest. \n\n## Priors\n\nprior_1 ~ beta(1,1)\n\nprior_2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalphas <- seq(0.001, 100, length.out = 1000)\nbetas <- ((1-(46/66))/(46/66)) * alphas\n\nparam_df <- tibble(alphas, betas)\nparam_df <- param_df |> mutate(vars = \n                    (alphas*betas)/((alphas+betas)^2*(alphas+betas+1)))\n\n\ntarget_var <- 0.05657^2\n\nparam_df <- param_df |> mutate(dist_to_target = abs(vars - target_var))\nparam_df |> filter(dist_to_target == min(dist_to_target))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  alphas betas    vars dist_to_target\n   <dbl> <dbl>   <dbl>          <dbl>\n1   45.3  19.7 0.00320     0.00000310\n```\n:::\n:::\n\n\nFor this informative prior I made the assumption that the clay-court match played in the previous year was preformed in comparable conditions to the match that I am interested in. Examples of conditions that I assume to be the same are weather (it is not considerably more sunny) and player ability (both players are not coming off of an injury or illness). \n\nprior_3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- seq(0.001, 300, length.out = 1000)\nbeta<- (0.25/0.75)*alpha\n\ntibble(alpha,beta)|>\n  mutate(prob = pbeta(0.7,alpha, beta),\n         dist = abs(prob - 0.02))|>\n  filter(dist == min(dist))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  alpha  beta   prob      dist\n  <dbl> <dbl>  <dbl>     <dbl>\n1  252.  83.9 0.0200 0.0000289\n```\n:::\n:::\n\n\nFor this informative prior I make the assumption that the sports announcer is not bias towards one of the players, and that the announcer is also accurate at estimating performance percentages. \n\nIn my code above, I also implement my own understand of \"almost sure\" by denoting the distance column with a value of 0.02, whereas another person could potentially believe that this value should be larger or smaller. \n\n\n### Graph of priors \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(0.001, 1, length.out = 1000)\nprior_1 <- dbeta(grid, 1, 1)\nprior_2 <- dbeta(grid, 45.3, 19.7)\nprior_3 <- dbeta(grid, 252, 83.9)\n\nplot_1 <- tibble(grid, prior_1)\nplot_2 <- tibble(grid, prior_2)\nplot_3 <- tibble(grid, prior_3)\n\nggplot(data = plot_1, aes(x = grid, y = prior_1)) +\n  geom_line() +\n  geom_line(data = plot_2, aes( x = grid, y = prior_2), col = \"blue\")+\n  geom_line(data = plot_3, aes(x = grid, y = prior_3), col = \"red\")+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Posteriors \n\ndata = 56/85\n\nFrom class - \n\nposterior ~ $beta( y_{obs}+ \\alpha, n-y_{obs}+\\beta)$\n\nprior 1 to posterior 1\n\npost_1 ~ beta(56 + 1, 85 - 56 + 1)\npost_1 ~ beta(57, 30)\n\nprior 2 to posterior 2\n\npost_2 ~ beta(56 + 45.3, 85 - 56 + 19.7 )\npost_2 ~ beta(101.3, 48.7)\n\nprior 3 to posterior 3\n\npost_3 ~ beta(56 + 253, 85 - 56 + 83.9 )\npost_3 ~ beta(309, 112.9)\n\n### Graph of posteriors \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- seq(0.001, 1, length.out = 1000)\npost_1 <- dbeta(grid, 57, 30)\npost_2 <- dbeta(grid, 101.3, 48.7)\npost_3 <- dbeta(grid, 309, 112.9)\n\nplot_1 <- tibble(grid, post_1)\nplot_2 <- tibble(grid, post_2)\nplot_3 <- tibble(grid, post_3)\n\nggplot(data = plot_1, aes(x = grid, y = post_1)) +\n  geom_line() +\n  geom_line(data = plot_2, aes( x = grid, y = post_2), col = \"blue\")+\n  geom_line(data = plot_3, aes(x = grid, y = post_3), col = \"red\")+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### Posterior means and 90% credible intervals\n\nPosterior_1\n\n::: {.cell}\n\n```{.r .cell-code}\n57/(57+30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6551724\n```\n:::\n\n```{.r .cell-code}\nqbeta(c(0.05, 0.95), 57, 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5697738 0.7364913\n```\n:::\n:::\n\n\nposterior mean = 0.655\n\ncredible interval = (0.5698 - 0.7365)\n\nPosterior_2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n101.3/(101.3+48.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6753333\n```\n:::\n\n```{.r .cell-code}\nqbeta(c(0.05, 0.95), 101.3, 48.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6113201 0.7366795\n```\n:::\n:::\n\n\nposterior mean = 0.675\n\ncredible interval = (0.6113 - 0.7367)\n\nPosterior_3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n309/(309 + 112.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.732401\n```\n:::\n\n```{.r .cell-code}\nqbeta(c(0.05, 0.95), 309, 112.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.696369 0.767179\n```\n:::\n:::\n\n\nposterior mean = 0.732\n\ncredible interval = (0.6964 - 0.7672)\n\n### Why do the posteriors look different? \n\nThe posteriors look different from each other because although they use the same data, they all came from different priors which means that their posterior distributions are directly connected to differing prior alphas and betas. This causes the staggering of means, and the difference in variance we can see in the wideness/narrowness of the distributions in the posterior plot. \n\n### Which would I choose?\n\nI would choose the 2nd posterior distribution which used the informative prior based on the previous years match results. I would choose this posterior distribution because I believe that utilizing the previous years data would be a good base of information for our question of interest, and it has a mean which is around the middle of the other two distributions. I also believe that since we know how notable Nadal is, it is not entirely fair to use an uninformative prior. Lastly, the low variance that can be seen in the last distribution makes me not believe this would be a beneficial posterior distribution because it does not hold a lot of room for error, and it relies heavily on the information that was provided in the prior. \n\n### Why does one posterior have a lower variance?\n\nThe last posterior distribution which was created using the sports announcers previous knowledge has the lowest variance, which can be seen by the extremely narrow peak in the plot. The reason that this has such a low variance is because if both alpha and beta parameters in a gamma distribution are large the variance will be small and in this posterior distribution the posterior alpha and beta are extremely large values (due to the large parameters from the prior distribution). \n## Conclusion \n\nIn this mini project, I found that the prior distribution will greatly influence your posterior distribution and therefore the conclusions that you can make about your parameter/question of interest. I can see that for binomial data, starting with large parameters in your prior will to a posterior model with low variance and a much more narrow credible interval, which seems unlikely to be helpful in situations where you may not know feel as confident in a topic (or in the information you have been given to create the prior). I also can conclude why using a non-informative prior would be beneficial in a case where you don't have a lot of prior experience/information because it returns a posterior model with more variance, and therefore returns a wider credible interval. This would be helpful as a  model to get an impression about what a proportion might be, and to then be able to potentially incorporate more data into this, which would lead to a stronger model. Above I explained that I believe the \"middle\" distribution (2nd prior) would be my distribution of choice and from this project I can see how using an informative prior, when the data is concrete and not speculated, potentially will lead to a good model which is not too biased towards the prior, and will return a solid credible interval and estimate for the proportion of interest. \n\nLastly, I can make a conclusion about our question of interest using the model that I would use! To do so I will interpret the credible interval. According to the model, there is a 90% probability that the proportion of points Rafael Nadal will win when he is serving against Noval Djokovic at the French Open is between 0.611 and 0.737. \n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}