---
title: "A Meaningful Story"
---

### Mini-Project Goal:

Portray your understanding of relevant vocabulary words by writing them into an understandable story.

### Story

Landing on the planet Gorbly was a rocky ride, the shuttle landed abruptly, shocking 10 of Earth’s most awarded scientists and statisticians who had descended here to determine the suitability of this new planet. Their goal was to secure a food resource before the remaining 500 humans arrived from Earth. Luckily through prior research they believed they had found the answer to their problem, a large watermelon-like fruit which contained every possible vitamin a human would need. What luck! Through initial surveillance they believed that the size and weight of the fruit followed a normal distribution, however they needed a strategy to estimate a parameter, since the true mean of the fruit’s weight remained unclear. They quickly began their assessment and chose a random sample of 10 groves which contained 30 fruits each. They decided that this was an appropriate number of random variables because each scientist could harvest and weigh the fruits in their own grove. Like the general population of these fruits they assumed that each of these variables followed a normal distribution. Now that they had all this data the scientists were lost, wondering how they could use this to come up with an estimate. Thank goodness for Kaitlin Heintzman, Earth’s top statistician who recalled that they could create an estimator that maximized the likelihood; by then inputting their sample they could find a more accurate estimate than something with less likelihood! Kaitlin had brought along her undergrad notes from math stat, and using this she identified a maximum likelihood estimator for the mean of this alien cuisine. The estimation for the mean ended up being just the mean of the data, which using the data they collected from their random sample created an estimate of 10 pounds. Another statistician on the trip scoffed, Willy Pomfrit was a known pessimist, and he believed he had a better estimator! He said that the estimator for the unknown parameter should be based on the expectation and variance of the lightest grove (the minimum). Using his estimators he calculated that the mean estimate was 5 pounds\*. Now they had a dilemma, which estimator was better?? Assessing the estimated mean, the bias of Kaitlin’s estimator was 0 as it was always the mean, which was better than Willy’s estimator which had a bias of 4\*. The next step was to assess the variance, although Kaitlin’s may be closer to the mean than Willy’s how did the spreads compare? After this computation it was found that Kaitlin’s estimator had a variance of 2, and Willy’s was a variance of 3\*. With these computations complete the group of scientists were convinced that Kaitlin’s was the better estimator of the two and they were almost convinced that they should choose hers. The crew only had 30 minutes before the second ship was supposed to enter Gorbly’s atmosphere and they needed to solidify their estimate!! The last test that would convince the crew was to check the consistency of the estimator. If they figured how to grow these fruits to an infinitely large population, would the expected value approach the true mean, and would the variance approach zero?? Kaitlin was confident in her estimator, but nervous as the minutes ticked down. Finally, the calculations were done, and they found the estimator WAS consistent! The crew was able to place confidence in this estimator and estimate and would be able to ensure that the rest of humanity would have an adequate food source on the planet Gorbly.

\*Note that the bias and variance for Willy’s estimator are completely made up for the plot of the story.
