---
title: "Final Reflection"
---

Throughout our time in this course, we have completed five mini-projects which directly correlate to the note sections that they follow. The completion of these mini-projects helped solidify the theoretical ideas that related to the main themes of the course.  We can also see that they relate to each other, this provided support in interconnecting the coursework sections we had completed, or were going to complete in the upcoming weeks. 

Beginning with mini-project 1, since this was the first section it really connected conceptually to the notes on sampling distributions. In this project, we simulated distributions for the minimum and maximum of various probability distributions. This connected both of the ideas we saw in the first note packet, sampling distributions and order statistics. In the labs for the first section, we used statistical simulation to look at how sampling distributions could change. This mini-project was directly similar to this concept, just a bit more complex as we used more than one type of probability distribution. The way that this project connected to other sections was through this idea of a sampling distribution. Through all of the other later sections this was a concept that continuously reappeared, and we continued to utilize statistical simulation in most of the labs and other mini-projects within the course. A specific connection that I found with mini project 1, 3, and 4 is the idea of altering parameters within a simulation to see how they change the outcomes.
As I have mentioned, we played with the probability distributions in mini-project 1, this was so see how the standard error and expected values would change. In mini-project 3, we changed the proportion and sample size parameters to see how the confidence intervals would change, and in mini-project 4, we changed the prior distributions to see how that would affect the posterior distribution. This aspect to the projects helped us connect theoretical concepts with actual changes via statistical simulation. The biggest takeaway that I have from the first mini-project is the impact that statistical simulation can play. Using this tool I was able to analyze the spread of different distributions and see how the max and min distributions would vary. Instead of just theoretically understanding it, I was able to really visualize it! From this project, I also was able to return to understanding the probability distributions we had covered in STAT 325, and to connect those ideas to this course. 

We then worked through Mini-project 2, which in hindsight seemed to connect all of the sections in the course, with potentially less of a connection to the section devoted to Bayesian statistics. This mini-project solidified our understanding of extremely important vocabulary, thus creating a foundation we could expand upon in later sections. A majority of these words had been introduced to us in our section on estimation (bias, consistent, variance, etc.), but there was also some which we had learned in section 1. As we continued to work through the class, we continued to see a lot of these words (such as likelihood, parameter). This meant that this mini-project also connected to a majority of the mini-projects that we did. For example, we explored sampling distribution simulation in the first mini-project, and the vocabulary that we used in mini-project 2 helped remind us of these concepts we had explored. In our other mini-projects this establishment of important vocabulary helped us worked through the simulations without any confusion on the theoretical concepts we had connected in our meaningful story (such as random sample or random variable). Although it may not connect directly to the concepts, the vocabulary we had connected was crucial in completing the later assignments correctly. Naturally, this mini-project connected the most to section 2 on estimation, where we derived a lot of estimators and estimates for different distributions and focused on their variance and bias. This project differed from the others because it didn't have any similar computations to the section that it followed, it was strictly completed to increase our knowledge of the vocabulary. I would say that one of my biggest takeaway that I took from the second mini-project is that being able to connect all the vocab words together in a meaningful story made the words more "real" to me. I was able to disconnect them from just our course and really process how they work together. Of course another connection is being able to understand these words from more than just a strict definition, I was able to connect them in a fake application to help solidify my understanding of them. 


Next we have mini-project 3, which connected to the section based on confidence intervals and it also had some overlap with section 5 on hypothesis testing. In this mini-project, we saw ways that the intervals would vary when given different parameters (proportion and sample size). This expanded on the notes and examples we worked through in section 3, where we learned how to calculate and interpret confidence intervals based on data, but the mini-project helped incorporate statistical simulation and understand how confidence intervals would react to unmet assumptions. This idea of breaking or meeting assumptions tied into the section on hypothesis testing, as we saw assumptions as being very important for test statistics which rely on the Central Limit Theorem. I felt that this mini-project connected to mini-project 5, by showing us how our CIs can be altered it connected to the idea portrayed in the paper we read for section 5, which addressed the idea that we rely so heavily on metrics which are based on just a sample of data. This paper critiqued that idea, and put into words the problems that could come from interpreting or relying on confidence intervals (and p-values) which do not fully meet assumptions. The biggest takeaways that I took from the third mini-project are directly related to what we explored, how broken assumptions will affect confidence intervals.  When these assumptions are broken it can alter the width and coverage rate of the interval, which then affects the accuracy of your confidence interval interpretation. Not only did this mini-project really show me the "danger" of unmet assumptions, it also made me reflect on how you should really look into the parameters used in other's results, because you could be getting shown an interval which conveys incorrect conclusions. 


Mini-project 4 was unique, as it really only connected to the section 4 coursework. This was because this section focused specifically on Bayesian statistics, and not frequentist statistics like all of the other sections. During this section, we focused on deriving posterior distributions from various prior distributions. These prior distributions were either non-informative or were created using a priori knowledge. Mini-project 4 directly relates to this idea as we used various informative and non-informative priors to display how they can alter the posterior distribution. Another way that this connected was through the creation of informative priors, which we could make based on knowledge from 'experts' and this was done in both our section coursework and the mini-project. When I discussed mini-project 1, I talked about how I found a connection between the first, fourth, and third mini-projects. It is difficult to find other connection between this mini-project and the others in concrete ways because mini-project 4 surrounds such a different collection of concepts. From the fourth mini-project, I learned how influential the prior distribution is to the posterior distribution, and that by using different prior distributions you can create entirely different posterior distributions (which will then affect your conclusions). The main idea I really took from this is how beneficial it can be to adjust your distributions based on pre-existing knowledge (or with the addition of more data). On that same tone, another idea I took away is how a prior distribution can really skew a conclusion, and this could be dangerous if the information used doesn't reflect reality. 


Our last mini-project was also quite unique, like the mini-project from section 2 it didn't have to do with computations. This mini-project was basically an analysis of the paper '*Moving to a world beyond p<0.05*' by Wasserstein, Schirm, and Lazar. In this project we focused on understanding why using p-values and confidence intervals may not be the best practice, and how these values are seen as extremely reliable when in reality they are made based on data, not the truth. In the notes for section 5, we spend a lot of time learning how to calculate and interpret p-values, so this paper added a layer to our understanding of how we should be drawing conclusions and looking at results. Although this project didn't directly connect to the computations in the course, I thought it was a nice closing project and an enriching paper that helped us not just understand the metrics we have learned about, but the ways they are used in research. In my paragraph for section 3, I spoke about how I believe that this mini-project connects directly to the third mini-project we completed. I think besides this, this mini-project does lightly connect to the others but in a much looser way. I think the way that this project connects to others in more in a cautionary way, and it reminds us to be aware that we are using simulations or samples of data, not the true population. Lastly, a main takeaway that I had from the fifth mini-project is that the reliance we have on p-values and confidence intervals is misguided and actually is limiting the scope of scientific research. What really stuck with me is the danger than strict division of significance can contribute to research studies, and I also learned some opinions on how we should try to change this and approach results in a different way. 




